name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for data collection
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/data_collection:latest -f Dockerfile.collection .

      - name: Build Docker image for data cleaning
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/data_cleaning:latest -f Dockerfile.cleaning .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/data_collection:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/data_cleaning:latest
